<h2 class="font-weight-bold">Agendar <?=($this->params->pageType=='vistoria'? 'Vistoria': 'Reparo')?></h2>
<form action="/agendamentos/store" class="my-2 bg-card p-5" method="post">
    <div class="form-group row mb-2">
        <label for="chamado" class="col-sm-1 col-form-label text-positionLabel">Chamado</label>
        <div class="col-sm-10">
            <select name="chamado" id="chamado" class="form-control input-theme">
                <?php
                foreach ($this->params->chamados as $chamado) {
                ?>
                    <option value="<?= $chamado->id ?>"><?= $chamado->motivo ?></option>
                <?php
                }
                ?>
            </select>
        </div>
    </div>
    <div class="form-group row mb-2">
        <label for="equipe" class="col-sm-1 col-form-label text-positionLabel">Equipe</label>
        <div class="col-sm-10">
            <select name="equipe" id="equipe" class="form-control input-theme">
                <?php
                foreach ($this->params->equipes as $equipe) {
                ?>
                    <option value="<?= $equipe->id ?>"><?= $equipe->nome ?></option>
                <?php
                }
                ?>
            </select>
        </div>
    </div>
    <div class="form-group row mb-2">
        <label for="data" class="col-sm-1 col-form-label text-positionLabel">Data</label>
        <div class="col-sm-10">
            <input type="date" class="form-control input-theme" min="<?= date('Y-m-d') ?>" name="data" value="<?= (isset($this->params->inputs['data'])) ? $this->params->inputs['data'] : date('Y-m-d') ?>" id="data" required>
        </div>
    </div>
    <input type="hidden" name="servico" value="<?=($this->params->pageType=='reparo')?'outro':'vistoria'?>">

    <div class="mt-4 text-right">
        <button type="submit" class="btn btn-theme">Agendar <i class="fas fa-calendar-alt ml-2"></i></button>
    </div>
</form>