<div class="row align-items-center mb-2">
    <div class="col-12">
        <h2 class="font-weight-bold">Todos Chamados</h2>
    </div>
</div>
<form class="rounded form-row bg-card m-1 align-items-end mb-3" action="" method="get">
    <div class="col-md-10 p-3">
        <div class="form-row">
            <label class="d-block" for="">Buscar Chamado</label>
            <input type="hidden" name="page" value="1">
            <input type="number" name="buscar" id="buscar" placeholder="Informe o Código do Chamado" value="<?=$this->params->buscar?>" class="form-control input-theme">
        </div>
    </div>
    <div class="col-md-2 p-3">
        <button type="submit" class="btn btn-theme w-100">Filtrar</button>
    </div>
</form>
<div class="table-responsive rounded">
    <table class="table rounded table-striped borded table-theme">
        <thead>
            <tr class="text-center">
                <th>Cód. Chamado</th>
                <th>Cliente</th>
                <th>Motivo</th>
                <th>Descrição</th>
                <th class="text-primary">Data de Abertura</th>
                <th class="text-warning">Agendado para</th>
                <th>Situação</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (count($this->params->chamados) > 0) {
                foreach ($this->params->chamados->sortByDesc("id") as $chamado) :
            ?>
                    <tr class="border-0 text-center" style="border:none!important">
                        <td><?= $chamado->id ?></td>
                        <td  class="text-lowercase"><?= $chamado->cliente->nome ?></td>
                        <td  class="text-lowercase"><?= $chamado->motivo ?></td>
                        <td><?= mb_strimwidth($chamado->descricao, 0, 50, "..."); ?></td>
                        <td class="text-primary"><?= date('d/m/Y H:i', strtotime($chamado->created_at)) ?></td>
                        <td class="text-warning"><?= (isset($chamado->dataAgendamento))?date('d/m/Y', strtotime($chamado->dataAgendamento)): "-----" ?></td>
                        <td><?php if ($chamado->status == "Pendente") {
                                echo $chamado->status . " <i class='fas fa-circle text-secondary'></i>";
                            } elseif ($chamado->status == "Aguardando reparo") {
                                echo $chamado->status . " <i class='fas fa-circle text-primary'></i>";
                            } elseif ($chamado->status == "Aguardando vistoria") {
                                echo $chamado->status . " <i class='fas fa-circle text-warning'></i>";
                            } elseif ($chamado->status == "Concluído") {
                                echo $chamado->status . " <i class='fas fa-circle text-success'></i>";
                            }  ?></td>
                        <td>
                            <a href="/chamados/<?= $chamado->id ?>/show" class="text-secondary mx-1" data-toggle="tooltip" data-placement="bottom" title="Visualizar"><i class="fas fa-eye"></i></a>
                        </td>
                    </tr>
            <?php
                endforeach;
            }
            ?>
        </tbody>
    </table>
</div>
<?php
if($this->params->chamadosCount==0){
    echo '<h4 class="text-center my-4">Nenhum registro encontrado!</h4>';
}
?>
<div class="my-2 d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item  disabled">
                <a class="page-link text-dark" href="#" tabindex="-1">Página <?=$this->params->pageAtual ?> de <?=$this->params->num_paginas ?></a>
            </li>
            <?php if ($this->params->pageAtual >= 2) { ?>
                <li class="page-item">
                    <a class="page-link text-dark" href="/chamados/all?page=<?=$this->params->pageAtual - 1; ?>&buscar=<?= isset($this->params->buscar) ? ($this->params->buscar) :  ""?>">
                        <i class="fas fa-chevron-left"></i></a>
                </li>
                <?php
            }
            for ($i = 1; $i <= 5; $i++) {
                $estilo = "";
                if ($this->params->pageAtual == $this->params->rowsPagina) {
                    $estilo = "active";
                }
                if ($this->params->rowsPagina < $this->params->num_paginas+1) {
                ?>
                    <li class="page-item <?=$estilo ?>">
                        <a class="page-link text-dark " href="/chamados/all?page=<?=$this->params->rowsPagina; ?>&buscar=<?= isset($this->params->buscar) ? ($this->params->buscar) :  ""?>">
                            <?=$this->params->rowsPagina++?>
                        </a>
                    </li>
                <?php
                }
            }
            if (($this->params->pageAtual ) < $this->params->num_paginas) { ?>
                <li class="page-item">
                    <a class="page-link text-dark" href="/chamados/all?page=<?=$this->params->pageAtual + 1; ?>&buscar=<?= isset($this->params->buscar) ? ($this->params->buscar) :  ""?>"><i class="fas fa-chevron-right"></i></a>
                </li>
            <?php } ?>
        </ul>
    </nav>
</div>