<h2 class="font-weight-bold">Editar Chamado</h2>
<form action="/chamados/<?=$this->params->chamado->id?>/update" class="my-2 bg-card p-5" method="post">
    <div class="form-group row mb-2">
        <label for="motivo" class="col-sm-1 col-form-label text-positionLabel">Motivo</label>
        <div class="col-sm-10">
            <input type="text" class="form-control input-theme" name="motivo"  value="<?=(isset($this->params->inputs['motivo']))?$this->params->inputs['motivo']:$this->params->chamado->motivo?>" id="motivo" placeholder="Informe o motivo" required>
        </div>
    </div>
    <div class="form-group row mb-2">
        <label for="descricao" class="col-sm-1 col-form-label text-positionLabel">Descrição</label>
        <div class="col-sm-10">
            <textarea name="descricao" placeholder="Descreva aqui o motivo do seu chamado..." class="form-control input-theme" id="descricao" cols="30" required rows="10"><?=(isset($this->params->inputs['descricao']))?$this->params->inputs['descricao']:$this->params->chamado->descricao?></textarea>
        </div>
    </div>
    <div class="mt-4 text-right">
        <button type="submit" class="btn btn-theme">Atualizar <i class="fas fa-redo-alt ml-2"></i></button>
    </div>
</form>