<h2 class="font-weight-bold">Início</h2>
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <?php
            if ($this->params->user['nv'] == 0) {
            ?>

                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/chamados/create" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-plus my-3 fa-4x "></i>
                                <h4>Abrir Chamado</h4>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/chamados" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-bell my-3 fa-4x "></i>
                                <h4>Meus Chamados</h4>
                            </div>
                        </a>
                    </div>
                </div>
            <?php
            }
            if ($this->params->user['nv'] >= 1) {
            ?>
                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/chamados/all" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-bell my-3 fa-4x "></i>
                                <h4>Todos Chamados</h4>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/equipes/show" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-users my-3 fa-4x "></i>
                                <h4>Minha Equipe</h4>
                            </div>
                        </a>
                    </div>
                </div>
            <?php
            }
            if ($this->params->user['nv'] == 2) {
            ?>
                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/equipes" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-sitemap my-3 fa-4x "></i>
                                <h4>Todas Equipes</h4>
                            </div>
                        </a>
                    </div>
                </div>


                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/agendamentos" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-calendar-alt my-3 fa-4x "></i>
                                <h4>Agendamentos</h4>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-4 mb-4">
                    <div class="bg-card card">
                        <a href="/funcionarios" class="link-dark">
                            <div class="text-center my-4 text-light">
                                <i class="fas fa-user-friends my-3 fa-4x "></i>
                                <h4>Funcionários</h4>
                            </div>
                        </a>
                    </div>
                </div>
            <?php
            }
            ?>
        </div>
    </div>
    <div class="col-md-4 mb-4">
        <div class="bg-card card p-4 h-100">
            <div class="d-flex justify-content-center align-items-center">
                <div class="mx-2 rounded-circle border border-theme border-2x userNav  p-5">
                    <i class="fas fa-user fa-4x"></i>
                </div>
            </div>
            <h4 class="text-center mt-2">Meus Dados</h4>
            <hr style="background: #ccc">
            <h5><strong>Nome: </strong><span><?= $this->params->user['nome'] ?></span></h5>
            <h5><strong>Email: </strong><span><?= $this->params->user['email'] ?></span></h5>
            <a href="/perfil" class="my-2 btn btn-theme">Editar <i class="fas fa-edit"></i></a>
        </div>
    </div>
</div>