<h5>Perfil Cliente</h5>
<div class="card shadow rounded bg-card  p-3 py-5 mb-4">
    <div class="d-flex justify-content-center align-items-center">
        <div class="mx-2 rounded-circle border border-theme border-2x userNav  p-5">
            <i class="fas fa-user fa-4x"></i>
        </div>
    </div>
    <h4 class="text-center mt-2  mb-4">Dados do Cliente</h4>
    <form action="/perfil/update" style="margin: auto; width: 90%" method="post">
        <div class="form-group w-100 mb-2">
            <label for="nome">Nome <strong class="text-danger">*</strong></label>
            <input type="text" class="form-control  input-theme" name="nome" required id="nome" value="<?= (isset($this->params->inputs['nome'])) ? $this->params->inputs['nome'] : $this->params->cliente['nome']; ?>" placeholder="">
        </div>
        <div class="form-group w-100 mb-2">
            <label for="endereco">Endereco</label>
            <input type="text" class="form-control  input-theme" name="endereco" value="<?= (isset($this->params->inputs['endereco'])) ? $this->params->inputs['endereco'] : $this->params->cliente['endereco']; ?>" id="endereco" placeholder="">
        </div>
        <div class="text-right mt-3">
            <a href="/perfil/resetPass" class="btn  mb-2 btn-secondary text-light">Alterar Senha <i class="fas fa-edit"></i></a>
            <button type="submit" class="btn  mb-2 btn-theme">Atualizar</button>
        </div>
    </form>
</div>