<h5>Perfil Funcionário</h5>
<div class="card shadow rounded bg-card  p-3 py-5 mb-4">
    <div class="d-flex justify-content-center align-items-center">
        <div class="mx-2 rounded-circle border border-theme border-2x userNav  p-5">
            <i class="fas fa-user fa-4x"></i>
        </div>
    </div>
    <h4 class="text-center mt-2  mb-4">Dados do Funcionário</h4>
    <form action="/perfil/update" style="margin: auto; width: 90%" method="post">
        <div class="form-group w-100 mb-2">
            <label for="nome">Nome <strong class="text-danger">*</strong></label>
            <input type="text" class="form-control  input-theme" name="nome" required id="nome" value="<?= (isset($this->params->inputs['nome'])) ? $this->params->inputs['nome'] : $this->params->funcionario['nome']; ?>" placeholder="">
        </div>
        <div class="form-group w-100 mb-2">
            <label for="funcao">Função <strong class="text-danger">*</strong></label>
            <input type="text" class="form-control  input-theme" name="funcao" value="<?= (isset($this->params->inputs['funcao'])) ? $this->params->inputs['funcao'] : $this->params->funcionario['funcao']; ?>" required id="funcao" placeholder="">
        </div>
        <div class="text-right mt-3">
            <a href="/perfil/resetPass" class="mb-2 btn btn-secondary text-light">Alterar Senha <i class="fas fa-edit"></i></a>
            <button type="submit" class="mb-2 btn btn-theme">Atualizar <i class="fas fa-redo-alt"></i></button>
        </div>
    </form>
</div>