<div class="row align-items-center mb-2">
    <div class="col-md-9">
        <h2 class="font-weight-bold">Funcionários</h2>
    </div>
    <div class="col-md-3 text-right">
        <a href="/funcionarios/create" class="btn btn-theme w-100">Adicionar Funcionário</a>
    </div>
</div>
<div class="table-responsive rounded">
    <table class="table rounded table-striped borded text-light table-theme">
        <thead>
            <tr class="text-center">
                <th>#</th>
                <th>Nome</th>
                <th>Função</th>
                <th>Equipe</th>
                <th>Nv. Acesso</th>
                <th>Alterar Nv. Acesso</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->params->funcionarios->where('id', '!=', $this->params->user['id']) as $funcionario) :
            ?>
                <tr class="text-center">
                    <td><?= $funcionario->id ?></td>
                    <td><?= $funcionario->nome ?></td>
                    <td><?= $funcionario->funcao ?></td>
                    <td><?= @$funcionario->equipe->nome ?></td>
                    <td><?= ($funcionario->nv_acesso == 1) ? "Comum" : "Administrador" ?></td>
                    <td>
                        <div class="custom-control custom-switch">
                            <input <?= ($funcionario->nv_acesso == 2) ? "checked" : "" ?> onclick="window.location.href = '/funcionarios/<?= $funcionario->id ?>/permissao'" type="checkbox" class="custom-control-input" id="permission<?= $funcionario->id ?>">
                            <label class="custom-control-label" for="permission<?= $funcionario->id ?>"></label>
                        </div>
                    </td>
                </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>
<?php
if ($this->params->funcionarios->count() == 0) {
    echo '<h4 class="text-center my-4">Nenhum registro encontrado!</h4>';
}
?>
<div class="my-2 d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item  disabled">
                <a class="page-link text-dark" href="#" tabindex="-1">Página <?= $this->params->pageAtual ?> de <?= $this->params->num_paginas ?></a>
            </li>
            <?php if ($this->params->pageAtual >= 2) { ?>
                <li class="page-item">
                    <a class="page-link text-dark" href="/funcionarios?page=<?= $this->params->pageAtual - 1; ?>">
                        <i class="fas fa-chevron-left"></i></a>
                </li>
                <?php
            }
            for ($i = 1; $i <= 5; $i++) {
                $estilo = "";
                if ($this->params->pageAtual == $this->params->rowsPagina) {
                    $estilo = "active";
                }
                if ($this->params->rowsPagina < $this->params->num_paginas + 1) {
                ?>
                    <li class="page-item <?= $estilo ?>">
                        <a class="page-link text-dark " href="/funcionarios?page=<?= $this->params->rowsPagina; ?>">
                            <?= $this->params->rowsPagina++ ?>
                        </a>
                    </li>
                <?php
                }
            }
            if (($this->params->pageAtual) < $this->params->num_paginas) { ?>
                <li class="page-item">
                    <a class="page-link text-dark" href="/funcionarios?page=<?= $this->params->pageAtual + 1; ?>"><i class="fas fa-chevron-right"></i></a>
                </li>
            <?php } ?>
        </ul>
    </nav>
</div>