<div class="row align-items-center mb-2">
    <div class="col-md-9">
        <h2 class="font-weight-bold">Equipes</h2>
    </div>
    <div class="col-md-3 text-right">
        <button class="btn btn-theme w-100" data-toggle="modal" data-target="#modalAddEquipe">Adicionar Equipe</button>
        <div class="modal fade" id="modalAddEquipe" tabindex="-1" role="dialog" aria-labelledby="modalAddEquipeLabel" aria-hidden="true">
            <div class="modal-dialog shadow modal-lg rounded" role="document">
                <div class="modal-content modalTheme ">
                    <form action="/equipes/store" method="post">
                        <div class="modal-header" style="border:none">
                            <h5 class="modal-title font-weight-bold" id="modalAddEquipeLabel">Adicionar Nova Equipe</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span class="text-light" aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-row pb-2">
                                <label for="nome">Nome</label>
                                <input type="text" required class="form-control input-theme" name="nome" id="nome">
                            </div>
                        </div>
                        <div class="modal-footer" style="border:none">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-theme">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- end modal-->
    </div>
</div>
<div class="table-responsive rounded">
    <table class="table rounded table-striped borded text-light table-theme">
        <thead>
            <tr class="text-center">
                <th>#</th>
                <th>Nome</th>
                <th class="text-primary">Chamados em Andamento</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->params->equipes as $equipe) :
            ?>
                <tr class="text-center">
                    <td><?= $equipe->id ?></td>
                    <td><?= $equipe->nome ?></td>
                    <td class="text-primary"><?= $equipe->chamado->where('status','!=','Pendente')->where('status','!=','Concluído')->count() ?></td>
                    <td class=>
                        <a href="/equipes/show?id=<?= $equipe['id'] ?>" class="text-secondary mx-1" data-toggle="tooltip" data-placement="bottom" title="Visualizar"><i class="fas fa-eye"></i></a>
                        <a href="/equipes/<?= $equipe['id'] ?>/edit" class="text-primary mx-1" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="fas fa-edit"></i></a>
                        <a href="/equipes/<?= $equipe['id'] ?>/delete" onclick="return confirm('Você deseja realmente remover esta equipe do sistema?')" class="text-danger mx-1" data-toggle="tooltip" data-placement="bottom" title="Remover"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>
<?php
if ($this->params->equipesCount == 0) {
    echo '<h4 class="text-center my-4">Nenhum registro encontrado!</h4>';
}
?>
<div class="my-2 d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item  disabled">
                <a class="page-link text-dark" href="#" tabindex="-1">Página <?= $this->params->pageAtual ?> de <?= $this->params->num_paginas ?></a>
            </li>
            <?php if ($this->params->pageAtual >= 2) { ?>
                <li class="page-item">
                    <a class="page-link text-dark" href="/equipes?page=<?= $this->params->pageAtual - 1; ?>">
                        <i class="fas fa-chevron-left"></i></a>
                </li>
                <?php
            }
            for ($i = 1; $i <= 5; $i++) {
                $estilo = "";
                if ($this->params->pageAtual == $this->params->rowsPagina) {
                    $estilo = "active";
                }
                if ($this->params->rowsPagina < $this->params->num_paginas + 1) {
                ?>
                    <li class="page-item <?= $estilo ?>">
                        <a class="page-link text-dark " href="/equipes?page=<?= $this->params->rowsPagina; ?>">
                            <?= $this->params->rowsPagina++ ?>
                        </a>
                    </li>
                <?php
                }
            }
            if (($this->params->pageAtual) < $this->params->num_paginas) { ?>
                <li class="page-item">
                    <a class="page-link text-dark" href="/equipes?page=<?= $this->params->pageAtual + 1; ?>"><i class="fas fa-chevron-right"></i></a>
                </li>
            <?php } ?>
        </ul>
    </nav>
</div>