<?php require_once __DIR__ . "/template/header.phtml"; ?>
<div class="container">
    <div class="rounded">
        <div class="row">
            <div class="col-md-6 py-4">
                <div class="m-5">
                    <form action="/register/store" id="formBox" method="post">
                    <h4 class="text-light mb-4 font-weight-bold">Crie uma conta</h4>
                        <div class="inputIcon">
                            <input type="email" name="email" id="email" class="input-login mb-2" value="<?php echo (isset($this->params->inputs['email'])) ? $this->params->inputs['email'] : ""; ?>" placeholder="Seu email" required>
                            <i class="fas fa-envelope text-muted"></i>
                        </div>
                        <div class="inputIcon">
                            <input type="text" name="nome" id="nome" class="input-login mb-2" value="<?php echo (isset($this->params->inputs['nome'])) ? $this->params->inputs['nome'] : ""; ?>" placeholder="Seu nome" required>
                            <i class="fas fa-user text-muted"></i>
                        </div>
                        <div class="inputIcon">
                            <input type="password" name="senha" id="senha" class="input-login mb-2" placeholder="Sua senha" required>
                            <i class="fas fa-lock text-muted"></i>
                        </div>
                        <button type="submit" class="input-login w-100 btn-theme px-3 my-3">REGISTRAR</button>
                    </form>
                </div>
            </div>
            <div class="col-md-6 d-flex align-items-center justify-content-center">
                <div class="py-5">
                    <h1 class="text-light font-weight-bold" style="font-size:40px">Crie uma conta para ter acesso ao sistema.</h1>
                    <p><a href="/login"><i class="fas fa-arrow-left mr-3"></i>  Já possui uma conta?</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require_once __DIR__ . "/template/footer.phtml"; ?>