<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$this->getPageTitle('-')?> CodeCerto</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/assets/css/style.css">
    <link rel="stylesheet" href="/public/assets/css/style-login.css">
    <link rel="stylesheet" href="/public/assets/toast/toast.css">
    <link rel="icon" href="/public/assets/img/favicon.ico" type="image/x-icon" />
</head>
<body>