<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Desafio Dimensão</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');

        body {
            padding: 0px;
            margin: 0px;
            background: #0b2239;
        }

        .container {
            font-family: 'Ubuntu', sans-serif;
            margin: 20px auto;
            width: 100%;
            display: flex;
            align-items: center;
            height: 92vh;
        }

        .desc {
            color: #aaa;
            font-size: 40px
        }
        .desc2 {
            color: #aaa;
            font-size: 20px
        }
        .center {
            width: 100%;
        }

        .text-center {
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="container text-center">
        <div class="center">
            <h4 class="desc">Verifique se a URL informada está correta!</h4>
            <h4 class="desc2"><a style="color: #3498db;" href="/">Voltar</a></h4>
        </div>
    </div>
</body>

</html>