<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->getPageTitle('-') ?> CodeCerto</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/assets/css/style.css">
    <link rel="stylesheet" href="/public/assets/css/theme.css">
    <link rel="stylesheet" href="/public/assets/toast/toast.css">
    <link rel="icon" href="/public/assets/img/favicon.ico" type="image/x-icon" />
</head>

<body>
    <?php require_once __DIR__ . "/template/header.phtml" ?>
    <div class="container-fluid">
        <div class="container-fluid">
            <?php $this->content() ?>
        </div>
    </div>
    <?php require_once __DIR__ . "/template/footer.phtml" ?>
    <script src="/public/assets/js/jquery.js"></script>
    <script src="/public/assets/js/functions.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/5e571f3815.js" crossorigin="anonymous"></script>
    <script src="/public/assets/toast/toast.js"></script>
    <?php
    if (isset($this->params->err)) {
        foreach ($this->params->err as $errs) :
    ?>
            <script type="text/javascript">
                $.toast({
                    heading: 'Error',
                    text: '<?= $errs ?>',
                    icon: 'error',
                    loader: true,
                    loaderBg: '#e74c3c',
                    position: 'bottom-right'
                })
            </script>
        <?php
        endforeach;
    }

    if (isset($this->params->success)) {
        foreach ($this->params->success as $successes) :

        ?>
            <script type="text/javascript">
                $.toast({
                    heading: 'Success',
                    text: '<?= $successes ?>',
                    icon: 'success',
                    loader: true,
                    loaderBg: '#2ecc71',
                    position: 'bottom-right'
                })
            </script>
        <?php
        endforeach;
    }

    if (isset($this->params->info)) {
        foreach ($this->params->info as $infos) :

        ?>
            <script type="text/javascript">
                $.toast({
                    heading: 'Info',
                    text: '<?= $infos ?>',
                    icon: 'info',
                    loader: true,
                    loaderBg: '#0abde3',
                    position: 'bottom-right'
                })
            </script>
    <?php
        endforeach;
    }
    ?>
</body>

</html>